// cd  C:\ChatTest01\data-transfer\userGRpc\src\main\java\proto
// protoc --java_out=.. --grpc-java_out=.. user.proto



syntax = "proto3";
//package org.example.usergrpc.user;
option java_package = "org.example.usergrpc.user";
option java_multiple_files=true;
option java_outer_classname = "UserProto";

// 메시지 정의
message User {
  string category = 1;   // 작업 종류
  string username = 2;   // 아이디
  string password = 3;   // 비밀번호
}

// 아이디 중복 검사 결과 메시지 정의
message UsergRpcResponse {
  bool validate = 1;  // 검증결과 (true, false)
  string message = 2; // 결과 메세지
}

//채팅 메시지 정의
message Message {
  string sender = 1;
  string message = 2;
  repeated string receiveLsit = 3;
}

message SavedMessage {
  repeated Message messageList = 1;
}

// 서비스 정의
service UserService {
  // 아이디 중복검사, 회원가입, 로그인
  rpc userIdChkAndJoinAndLogin (User) returns (UsergRpcResponse);

  //메세지 전송 서비스
  rpc sendMessage (Message) returns (Message);

  //저장된 메세지 가지고 오기
  rpc savedMessage (Message) returns (SavedMessage);

}