// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

public interface IdCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.usergrpc.user.IdCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 아이디 중복 여부 (true: 중복, false: 사용 가능)
   * </pre>
   *
   * <code>bool isDuplicate = 1;</code>
   * @return The isDuplicate.
   */
  boolean getIsDuplicate();

  /**
   * <pre>
   * 상태 메시지
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 상태 메시지
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
