// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

public interface LoginUserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.usergrpc.user.LoginUser)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool login = 1;</code>
   * @return The login.
   */
  boolean getLogin();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
