// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

public interface SavedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SavedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Message messageList = 1;</code>
   */
  java.util.List<org.example.usergrpc.user.Message> 
      getMessageListList();
  /**
   * <code>repeated .Message messageList = 1;</code>
   */
  org.example.usergrpc.user.Message getMessageList(int index);
  /**
   * <code>repeated .Message messageList = 1;</code>
   */
  int getMessageListCount();
  /**
   * <code>repeated .Message messageList = 1;</code>
   */
  java.util.List<? extends org.example.usergrpc.user.MessageOrBuilder> 
      getMessageListOrBuilderList();
  /**
   * <code>repeated .Message messageList = 1;</code>
   */
  org.example.usergrpc.user.MessageOrBuilder getMessageListOrBuilder(
      int index);
}
