// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

public interface TransFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TransFile)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @return A list containing the receiveLsit.
   */
  java.util.List<java.lang.String>
      getReceiveLsitList();
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @return The count of receiveLsit.
   */
  int getReceiveLsitCount();
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @param index The index of the element to return.
   * @return The receiveLsit at the given index.
   */
  java.lang.String getReceiveLsit(int index);
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the receiveLsit at the given index.
   */
  com.google.protobuf.ByteString
      getReceiveLsitBytes(int index);

  /**
   * <code>string oriFileName = 4;</code>
   * @return The oriFileName.
   */
  java.lang.String getOriFileName();
  /**
   * <code>string oriFileName = 4;</code>
   * @return The bytes for oriFileName.
   */
  com.google.protobuf.ByteString
      getOriFileNameBytes();

  /**
   * <code>string ext = 5;</code>
   * @return The ext.
   */
  java.lang.String getExt();
  /**
   * <code>string ext = 5;</code>
   * @return The bytes for ext.
   */
  com.google.protobuf.ByteString
      getExtBytes();

  /**
   * <code>string size = 6;</code>
   * @return The size.
   */
  java.lang.String getSize();
  /**
   * <code>string size = 6;</code>
   * @return The bytes for size.
   */
  com.google.protobuf.ByteString
      getSizeBytes();

  /**
   * <code>bytes file = 7;</code>
   * @return The file.
   */
  com.google.protobuf.ByteString getFile();
}
