// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

/**
 * Protobuf type {@code TransFile}
 */
public final class TransFile extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:TransFile)
    TransFileOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      TransFile.class.getName());
  }
  // Use TransFile.newBuilder() to construct.
  private TransFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TransFile() {
    sender_ = "";
    message_ = "";
    receiveLsit_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    oriFileName_ = "";
    ext_ = "";
    size_ = "";
    file_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.usergrpc.user.UserProto.internal_static_TransFile_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.usergrpc.user.UserProto.internal_static_TransFile_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.usergrpc.user.TransFile.class, org.example.usergrpc.user.TransFile.Builder.class);
  }

  public static final int SENDER_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object sender_ = "";
  /**
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  @java.lang.Override
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVELSIT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList receiveLsit_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @return A list containing the receiveLsit.
   */
  public com.google.protobuf.ProtocolStringList
      getReceiveLsitList() {
    return receiveLsit_;
  }
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @return The count of receiveLsit.
   */
  public int getReceiveLsitCount() {
    return receiveLsit_.size();
  }
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @param index The index of the element to return.
   * @return The receiveLsit at the given index.
   */
  public java.lang.String getReceiveLsit(int index) {
    return receiveLsit_.get(index);
  }
  /**
   * <code>repeated string receiveLsit = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the receiveLsit at the given index.
   */
  public com.google.protobuf.ByteString
      getReceiveLsitBytes(int index) {
    return receiveLsit_.getByteString(index);
  }

  public static final int ORIFILENAME_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object oriFileName_ = "";
  /**
   * <code>string oriFileName = 4;</code>
   * @return The oriFileName.
   */
  @java.lang.Override
  public java.lang.String getOriFileName() {
    java.lang.Object ref = oriFileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oriFileName_ = s;
      return s;
    }
  }
  /**
   * <code>string oriFileName = 4;</code>
   * @return The bytes for oriFileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOriFileNameBytes() {
    java.lang.Object ref = oriFileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oriFileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ext_ = "";
  /**
   * <code>string ext = 5;</code>
   * @return The ext.
   */
  @java.lang.Override
  public java.lang.String getExt() {
    java.lang.Object ref = ext_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ext_ = s;
      return s;
    }
  }
  /**
   * <code>string ext = 5;</code>
   * @return The bytes for ext.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtBytes() {
    java.lang.Object ref = ext_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ext_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object size_ = "";
  /**
   * <code>string size = 6;</code>
   * @return The size.
   */
  @java.lang.Override
  public java.lang.String getSize() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      size_ = s;
      return s;
    }
  }
  /**
   * <code>string size = 6;</code>
   * @return The bytes for size.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSizeBytes() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      size_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_FIELD_NUMBER = 7;
  private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes file = 7;</code>
   * @return The file.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getFile() {
    return file_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sender_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, sender_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, message_);
    }
    for (int i = 0; i < receiveLsit_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, receiveLsit_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(oriFileName_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, oriFileName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ext_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, ext_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(size_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, size_);
    }
    if (!file_.isEmpty()) {
      output.writeBytes(7, file_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(sender_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, sender_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, message_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < receiveLsit_.size(); i++) {
        dataSize += computeStringSizeNoTag(receiveLsit_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getReceiveLsitList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(oriFileName_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, oriFileName_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ext_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, ext_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(size_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, size_);
    }
    if (!file_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(7, file_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.usergrpc.user.TransFile)) {
      return super.equals(obj);
    }
    org.example.usergrpc.user.TransFile other = (org.example.usergrpc.user.TransFile) obj;

    if (!getSender()
        .equals(other.getSender())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getReceiveLsitList()
        .equals(other.getReceiveLsitList())) return false;
    if (!getOriFileName()
        .equals(other.getOriFileName())) return false;
    if (!getExt()
        .equals(other.getExt())) return false;
    if (!getSize()
        .equals(other.getSize())) return false;
    if (!getFile()
        .equals(other.getFile())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getReceiveLsitCount() > 0) {
      hash = (37 * hash) + RECEIVELSIT_FIELD_NUMBER;
      hash = (53 * hash) + getReceiveLsitList().hashCode();
    }
    hash = (37 * hash) + ORIFILENAME_FIELD_NUMBER;
    hash = (53 * hash) + getOriFileName().hashCode();
    hash = (37 * hash) + EXT_FIELD_NUMBER;
    hash = (53 * hash) + getExt().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize().hashCode();
    hash = (37 * hash) + FILE_FIELD_NUMBER;
    hash = (53 * hash) + getFile().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.usergrpc.user.TransFile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.usergrpc.user.TransFile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.usergrpc.user.TransFile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.usergrpc.user.TransFile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.usergrpc.user.TransFile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code TransFile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TransFile)
      org.example.usergrpc.user.TransFileOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.usergrpc.user.UserProto.internal_static_TransFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.usergrpc.user.UserProto.internal_static_TransFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.usergrpc.user.TransFile.class, org.example.usergrpc.user.TransFile.Builder.class);
    }

    // Construct using org.example.usergrpc.user.TransFile.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      sender_ = "";
      message_ = "";
      receiveLsit_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      oriFileName_ = "";
      ext_ = "";
      size_ = "";
      file_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.usergrpc.user.UserProto.internal_static_TransFile_descriptor;
    }

    @java.lang.Override
    public org.example.usergrpc.user.TransFile getDefaultInstanceForType() {
      return org.example.usergrpc.user.TransFile.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.usergrpc.user.TransFile build() {
      org.example.usergrpc.user.TransFile result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.usergrpc.user.TransFile buildPartial() {
      org.example.usergrpc.user.TransFile result = new org.example.usergrpc.user.TransFile(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.usergrpc.user.TransFile result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.sender_ = sender_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        receiveLsit_.makeImmutable();
        result.receiveLsit_ = receiveLsit_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.oriFileName_ = oriFileName_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ext_ = ext_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.file_ = file_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.usergrpc.user.TransFile) {
        return mergeFrom((org.example.usergrpc.user.TransFile)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.usergrpc.user.TransFile other) {
      if (other == org.example.usergrpc.user.TransFile.getDefaultInstance()) return this;
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.receiveLsit_.isEmpty()) {
        if (receiveLsit_.isEmpty()) {
          receiveLsit_ = other.receiveLsit_;
          bitField0_ |= 0x00000004;
        } else {
          ensureReceiveLsitIsMutable();
          receiveLsit_.addAll(other.receiveLsit_);
        }
        onChanged();
      }
      if (!other.getOriFileName().isEmpty()) {
        oriFileName_ = other.oriFileName_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getExt().isEmpty()) {
        ext_ = other.ext_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getSize().isEmpty()) {
        size_ = other.size_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getFile() != com.google.protobuf.ByteString.EMPTY) {
        setFile(other.getFile());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              sender_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureReceiveLsitIsMutable();
              receiveLsit_.add(s);
              break;
            } // case 26
            case 34: {
              oriFileName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              ext_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              size_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              file_ = input.readBytes();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object sender_ = "";
    /**
     * <code>string sender = 1;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender = 1;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender = 1;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      sender_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      sender_ = getDefaultInstance().getSender();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string sender = 1;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      sender_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList receiveLsit_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureReceiveLsitIsMutable() {
      if (!receiveLsit_.isModifiable()) {
        receiveLsit_ = new com.google.protobuf.LazyStringArrayList(receiveLsit_);
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @return A list containing the receiveLsit.
     */
    public com.google.protobuf.ProtocolStringList
        getReceiveLsitList() {
      receiveLsit_.makeImmutable();
      return receiveLsit_;
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @return The count of receiveLsit.
     */
    public int getReceiveLsitCount() {
      return receiveLsit_.size();
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @param index The index of the element to return.
     * @return The receiveLsit at the given index.
     */
    public java.lang.String getReceiveLsit(int index) {
      return receiveLsit_.get(index);
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the receiveLsit at the given index.
     */
    public com.google.protobuf.ByteString
        getReceiveLsitBytes(int index) {
      return receiveLsit_.getByteString(index);
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @param index The index to set the value at.
     * @param value The receiveLsit to set.
     * @return This builder for chaining.
     */
    public Builder setReceiveLsit(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReceiveLsitIsMutable();
      receiveLsit_.set(index, value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @param value The receiveLsit to add.
     * @return This builder for chaining.
     */
    public Builder addReceiveLsit(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureReceiveLsitIsMutable();
      receiveLsit_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @param values The receiveLsit to add.
     * @return This builder for chaining.
     */
    public Builder addAllReceiveLsit(
        java.lang.Iterable<java.lang.String> values) {
      ensureReceiveLsitIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, receiveLsit_);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiveLsit() {
      receiveLsit_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string receiveLsit = 3;</code>
     * @param value The bytes of the receiveLsit to add.
     * @return This builder for chaining.
     */
    public Builder addReceiveLsitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureReceiveLsitIsMutable();
      receiveLsit_.add(value);
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object oriFileName_ = "";
    /**
     * <code>string oriFileName = 4;</code>
     * @return The oriFileName.
     */
    public java.lang.String getOriFileName() {
      java.lang.Object ref = oriFileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oriFileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oriFileName = 4;</code>
     * @return The bytes for oriFileName.
     */
    public com.google.protobuf.ByteString
        getOriFileNameBytes() {
      java.lang.Object ref = oriFileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oriFileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oriFileName = 4;</code>
     * @param value The oriFileName to set.
     * @return This builder for chaining.
     */
    public Builder setOriFileName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      oriFileName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string oriFileName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOriFileName() {
      oriFileName_ = getDefaultInstance().getOriFileName();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string oriFileName = 4;</code>
     * @param value The bytes for oriFileName to set.
     * @return This builder for chaining.
     */
    public Builder setOriFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      oriFileName_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object ext_ = "";
    /**
     * <code>string ext = 5;</code>
     * @return The ext.
     */
    public java.lang.String getExt() {
      java.lang.Object ref = ext_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ext_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ext = 5;</code>
     * @return The bytes for ext.
     */
    public com.google.protobuf.ByteString
        getExtBytes() {
      java.lang.Object ref = ext_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ext = 5;</code>
     * @param value The ext to set.
     * @return This builder for chaining.
     */
    public Builder setExt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ext_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string ext = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExt() {
      ext_ = getDefaultInstance().getExt();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string ext = 5;</code>
     * @param value The bytes for ext to set.
     * @return This builder for chaining.
     */
    public Builder setExtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ext_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object size_ = "";
    /**
     * <code>string size = 6;</code>
     * @return The size.
     */
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string size = 6;</code>
     * @return The bytes for size.
     */
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string size = 6;</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      size_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string size = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      size_ = getDefaultInstance().getSize();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string size = 6;</code>
     * @param value The bytes for size to set.
     * @return This builder for chaining.
     */
    public Builder setSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      size_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString file_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes file = 7;</code>
     * @return The file.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getFile() {
      return file_;
    }
    /**
     * <code>bytes file = 7;</code>
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      file_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bytes file = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFile() {
      bitField0_ = (bitField0_ & ~0x00000040);
      file_ = getDefaultInstance().getFile();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:TransFile)
  }

  // @@protoc_insertion_point(class_scope:TransFile)
  private static final org.example.usergrpc.user.TransFile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.usergrpc.user.TransFile();
  }

  public static org.example.usergrpc.user.TransFile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TransFile>
      PARSER = new com.google.protobuf.AbstractParser<TransFile>() {
    @java.lang.Override
    public TransFile parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TransFile> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TransFile> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.usergrpc.user.TransFile getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

