// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

public final class UserOuterClass {
  private UserOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      UserOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_usergrpc_user_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_usergrpc_user_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_usergrpc_user_IdCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_usergrpc_user_IdCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_usergrpc_user_JoinUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_usergrpc_user_JoinUser_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_usergrpc_user_loginUser_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_example_usergrpc_user_loginUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\031org.example.usergrpc.user\"" +
      "<\n\004User\022\020\n\010category\030\001 \001(\t\022\020\n\010username\030\002 " +
      "\001(\t\022\020\n\010password\030\003 \001(\t\"7\n\017IdCheckResponse" +
      "\022\023\n\013isDuplicate\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"1" +
      "\n\010JoinUser\022\024\n\014joinvalidate\030\001 \001(\010\022\017\n\007mess" +
      "age\030\002 \001(\t\"+\n\tloginUser\022\r\n\005login\030\001 \001(\010\022\017\n" +
      "\007message\030\002 \001(\t2\201\002\n\013UserService\022T\n\005idChk\022" +
      "\037.org.example.usergrpc.user.User\032*.org.e" +
      "xample.usergrpc.user.IdCheckResponse\022L\n\004" +
      "join\022\037.org.example.usergrpc.user.User\032#." +
      "org.example.usergrpc.user.JoinUser\022N\n\005lo" +
      "gin\022\037.org.example.usergrpc.user.User\032$.o" +
      "rg.example.usergrpc.user.loginUserB\002P\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_usergrpc_user_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_usergrpc_user_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_usergrpc_user_User_descriptor,
        new java.lang.String[] { "Category", "Username", "Password", });
    internal_static_org_example_usergrpc_user_IdCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_usergrpc_user_IdCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_usergrpc_user_IdCheckResponse_descriptor,
        new java.lang.String[] { "IsDuplicate", "Message", });
    internal_static_org_example_usergrpc_user_JoinUser_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_example_usergrpc_user_JoinUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_usergrpc_user_JoinUser_descriptor,
        new java.lang.String[] { "Joinvalidate", "Message", });
    internal_static_org_example_usergrpc_user_loginUser_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_example_usergrpc_user_loginUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_example_usergrpc_user_loginUser_descriptor,
        new java.lang.String[] { "Login", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
