// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.usergrpc.user;

public final class UserProto {
  private UserProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "",
      UserProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UsergRpcResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UsergRpcResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SavedMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SavedMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\"<\n\004User\022\020\n\010category\030\001 \001(\t\022\020" +
      "\n\010username\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\"5\n\020Us" +
      "ergRpcResponse\022\020\n\010validate\030\001 \001(\010\022\017\n\007mess" +
      "age\030\002 \001(\t\"?\n\007Message\022\016\n\006sender\030\001 \001(\t\022\017\n\007" +
      "message\030\002 \001(\t\022\023\n\013receiveLsit\030\003 \003(\t\"-\n\014Sa" +
      "vedMessage\022\035\n\013messageList\030\001 \003(\0132\010.Messag" +
      "e2\217\001\n\013UserService\0224\n\030userIdChkAndJoinAnd" +
      "Login\022\005.User\032\021.UsergRpcResponse\022!\n\013sendM" +
      "essage\022\010.Message\032\010.Message\022\'\n\014savedMessa" +
      "ge\022\010.Message\032\r.SavedMessageB(\n\031org.examp" +
      "le.usergrpc.userB\tUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Category", "Username", "Password", });
    internal_static_UsergRpcResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UsergRpcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UsergRpcResponse_descriptor,
        new java.lang.String[] { "Validate", "Message", });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "Sender", "Message", "ReceiveLsit", });
    internal_static_SavedMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SavedMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SavedMessage_descriptor,
        new java.lang.String[] { "MessageList", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
