// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: user.proto
// Protobuf Java Version: 4.29.0

package org.example.back.user;

public interface UsergRpcResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UsergRpcResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 검증결과 (true, false)
   * </pre>
   *
   * <code>bool validate = 1;</code>
   * @return The validate.
   */
  boolean getValidate();

  /**
   * <pre>
   * 결과 메세지
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * 결과 메세지
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
